/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pousada.conexao;
import static pousada.conexao.statement;
import pousada.item;


/**
 *
 * @author Aluno
 */
public class tela2 extends javax.swing.JFrame {

    /**
     * Creates new form tela2
     */
    public tela2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbcodigo = new javax.swing.JLabel();
        lbnome = new javax.swing.JTextField();
        lbcpf = new javax.swing.JTextField();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        lbfs = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbendereco = new javax.swing.JTextField();
        lbtelefone = new javax.swing.JTextField();
        lbregiao = new javax.swing.JTextField();
        lbnumerop = new javax.swing.JTextField();
        lbidade = new javax.swing.JTextField();
        lbtipoquarto = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox<>();
        lbcheck = new datechooser.beans.DateChooserCombo();
        jLabel17 = new javax.swing.JLabel();
        lbquarto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        quadra = new javax.swing.JTextField();
        reservadata1 = new datechooser.beans.DateChooserCombo();

        jLabel15.setText("jLabel15");

        jLabel19.setText("jLabel19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Voltar");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 160, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código da reserva:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de quarto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Endereço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Número de telefone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Região da pousada:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Número de pessoas:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Formas de pagamento:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 190, 20));

        jLabel10.setBackground(new java.awt.Color(102, 102, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Criar reserva");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 180, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Check-in:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Check-out:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 366, -1, 10));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Idade:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 250, 10));

        lbcodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbcodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 60, 20));

        lbnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbnomeActionPerformed(evt);
            }
        });
        getContentPane().add(lbnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 170, -1));
        getContentPane().add(lbcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, 20));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 130, 150));
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 120, 150));
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -50, 220, 230));
        getContentPane().add(lbfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -50, 300, 250));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Nome:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));
        getContentPane().add(lbendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 120, -1));
        getContentPane().add(lbtelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 130, -1));

        lbregiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbregiaoActionPerformed(evt);
            }
        });
        getContentPane().add(lbregiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 130, -1));
        getContentPane().add(lbnumerop, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 130, -1));

        lbidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbidadeActionPerformed(evt);
            }
        });
        getContentPane().add(lbidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 80, -1));

        lbtipoquarto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbtipoquarto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standart ", "Premium ", "Deluxe" }));
        lbtipoquarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbtipoquartoActionPerformed(evt);
            }
        });
        getContentPane().add(lbtipoquarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 110, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIX", "Cartão de crédito", "Cartão de débito", "Boleto" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 140, 20));
        getContentPane().add(lbcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Quarto:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        lbquarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbquartoActionPerformed(evt);
            }
        });
        getContentPane().add(lbquarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 100, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Quadra:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, -1, -1));
        getContentPane().add(quadra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 90, -1));
        getContentPane().add(reservadata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        tela1 dacz = new tela1();
    dacz.setVisible(true);
    dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      pegaCodigo();
    lbcodigo.setText(String.valueOf(seq));
    
    ImageIcon img = new ImageIcon(this.getClass().getResource("/img/monte.png"));
    Image imag = img.getImage().getScaledInstance(lbfs.getWidth(), lbfs.getHeight(), Image.SCALE_DEFAULT);
    lbfs.setIcon(new ImageIcon(imag));
        
     ImageIcon img1 = new ImageIcon(this.getClass().getResource("/img/p1.png"));
    Image imag1 = img1.getImage().getScaledInstance(p1.getWidth(), p1.getHeight(), Image.SCALE_DEFAULT);
    p1.setIcon(new ImageIcon(imag1));
    
    ImageIcon img2 = new ImageIcon(this.getClass().getResource("/img/p3.png"));
    Image imag2 = img2.getImage().getScaledInstance(p2.getWidth(), p2.getHeight(), Image.SCALE_DEFAULT);
    p2.setIcon(new ImageIcon(imag2));
    
    ImageIcon img3 = new ImageIcon(this.getClass().getResource("/img/passaro .png"));
    Image imag3 = img3.getImage().getScaledInstance(p3.getWidth(), p3.getHeight(), Image.SCALE_DEFAULT);
    p3.setIcon(new ImageIcon(imag3));
    
    }
    private void cargaCombo()
    {
         try 
        {              
               lbtipoquarto.removeAllItems();
              conexao objetoBD = new conexao();
              String sql = "SELECT tb03_tipo_quarto FROM tb03_reservas"; 
              objetoBD.conectar();
       
              ResultSet rs = statement.executeQuery(sql);
        
              String id = null;
              String nom = null;
        
             lbtipoquarto.addItem(new item(id, nom)); 
        
              while (rs.next())
              {
            id = rs.getString("tb03_tipo_quarto");  
                nom = rs.getString("tb03_tipo_quarto");  
                
                lbtipoquarto.addItem(new item(id, nom));
              }
              objetoBD.desconectar();
              statement.close(); 
        }
               
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
       
   

    
    }//GEN-LAST:event_formWindowOpened

    int seq=0;
    conexao comb;
    
     private void pegaCodigo()
    {
        String sql = "SELECT MAX(tb03_codigo) FROM tb03_reservas;";            
        try{
        seq = 1;   
        comb = new conexao();
        comb.conectar();
        ResultSet rs = statement.executeQuery(sql);         
        if (rs.next())         {
             seq = rs.getInt("MAX(tb03_codigo)");
        }        
        seq = seq + 1;         
        comb.desconectar();
        }
        catch (Exception e){
             System.out.println(e.getMessage());
         }
    }
    
    private void lbnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbnomeActionPerformed

    private void lbregiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbregiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbregiaoActionPerformed

    private void lbidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbidadeActionPerformed

    private void lbtipoquartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbtipoquartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbtipoquartoActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
   


    
       String sql = "INSERT INTO tb03_reservas (tb03_codigo, tb03_regiao, tb03_quarto, tb03_dt_reserva, tb03_cpf, tb03_tipo_quarto, tb03_quadra, tb03_nome, tb03_endereco, tb03_numerop, tb03_telefone, tb03_idade, tb03_dt_check) "
               +"VALUES ('"+lbcodigo.getText()+"', '"+lbregiao.getText()+"',  '"+lbquarto.getText()+"', '"+lbcheck.getText()+"','"+lbcpf.getText()+"','"+lbtipoquarto.getSelectedItem()+"', '"+quadra.getText()+"', '"+lbnome.getText()+"', '"+lbendereco.getText()+"', '"+Integer.parseInt(lbnumerop.getText())+"', '"+Integer.parseInt(lbtelefone.getText())+"', '"+Integer.parseInt(lbidade.getText())+"', '"+lbcheck.getText()+"')";
         System.out.println(sql);
        try{
        
        conexao objetoBD = new conexao();
        objetoBD.conectar();
        int qtdreg = objetoBD.runSQL(sql);
        objetoBD.desconectar();
        if (qtdreg == 0) 
           JOptionPane.showMessageDialog(null, "Reserva ja efetuada");
        else 
           JOptionPane.showMessageDialog(null, "Inclusão Efetuada");
        }   
        catch (Exception e){
             System.out.println(e.getMessage());
         }
    
        

        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void lbquartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbquartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbquartoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private datechooser.beans.DateChooserCombo lbcheck;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JTextField lbcpf;
    private javax.swing.JTextField lbendereco;
    private javax.swing.JLabel lbfs;
    private javax.swing.JTextField lbidade;
    private javax.swing.JTextField lbnome;
    private javax.swing.JTextField lbnumerop;
    private javax.swing.JTextField lbquarto;
    private javax.swing.JTextField lbregiao;
    private javax.swing.JTextField lbtelefone;
    private javax.swing.JComboBox lbtipoquarto;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JTextField quadra;
    private datechooser.beans.DateChooserCombo reservadata1;
    // End of variables declaration//GEN-END:variables
}
