/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import pousada.conexao;
import static pousada.conexao.statement;

/**
 *
 * @author Aluno
 */
public class tela6 extends javax.swing.JFrame {

    /**
     * Creates new form tela6
     */
    public tela6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbfs = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbtipoquarto = new javax.swing.JLabel();
        lbnome = new javax.swing.JLabel();
        lbcpf = new javax.swing.JLabel();
        lbendereco = new javax.swing.JLabel();
        lbnumero = new javax.swing.JLabel();
        lbregiao = new javax.swing.JLabel();
        lbnum = new javax.swing.JLabel();
        lbcheck = new javax.swing.JLabel();
        lbcheckout = new javax.swing.JLabel();
        lbcolocacod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código da reserva:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Endereço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Número de telefone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Região da pousada:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Número de pessoas:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Check-in:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Tipo de quarto:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Nome:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));
        getContentPane().add(lbfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -130, 300, 250));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, 150));
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 120, 150));
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -40, 220, 230));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Voltar");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 160, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 70, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Check-out:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        lbtipoquarto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbtipoquarto.setText("XXX");
        getContentPane().add(lbtipoquarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        lbnome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbnome.setText("XXX");
        getContentPane().add(lbnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        lbcpf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbcpf.setText("XXX");
        getContentPane().add(lbcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        lbendereco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbendereco.setText("XXX");
        getContentPane().add(lbendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        lbnumero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbnumero.setText("XXX");
        getContentPane().add(lbnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        lbregiao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbregiao.setText("XXX");
        getContentPane().add(lbregiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        lbnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbnum.setText("XXX");
        getContentPane().add(lbnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        lbcheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbcheck.setText("XXX");
        getContentPane().add(lbcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        lbcheckout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbcheckout.setText("XXX");
        getContentPane().add(lbcheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        lbcolocacod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbcolocacodActionPerformed(evt);
            }
        });
        lbcolocacod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbcolocacodKeyPressed(evt);
            }
        });
        getContentPane().add(lbcolocacod, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        tela1 dacz = new tela1();
        dacz.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         ImageIcon img = new ImageIcon(this.getClass().getResource("/img/monte.png"));
    Image imag = img.getImage().getScaledInstance(lbfs.getWidth(), lbfs.getHeight(), Image.SCALE_DEFAULT);
    lbfs.setIcon(new ImageIcon(imag));
        
     ImageIcon img1 = new ImageIcon(this.getClass().getResource("/img/p1.png"));
    Image imag1 = img1.getImage().getScaledInstance(p1.getWidth(), p1.getHeight(), Image.SCALE_DEFAULT);
    p1.setIcon(new ImageIcon(imag1));
    
    ImageIcon img2 = new ImageIcon(this.getClass().getResource("/img/p3.png"));
    Image imag2 = img2.getImage().getScaledInstance(p2.getWidth(), p2.getHeight(), Image.SCALE_DEFAULT);
    p2.setIcon(new ImageIcon(imag2));
    
    ImageIcon img3 = new ImageIcon(this.getClass().getResource("/img/passaro .png"));
    Image imag3 = img3.getImage().getScaledInstance(p3.getWidth(), p3.getHeight(), Image.SCALE_DEFAULT);
    p3.setIcon(new ImageIcon(imag3));
    }
     private void carregaTela() {

        try {
            String sql = "SELECT * FROM tb03_reservas WHERE tb03_codigo = " + lbcolocacod.getText();
            ;

            conexao banco = new conexao();

            banco.conectar();

            ResultSet resultSet = statement.executeQuery(sql);

            while (resultSet.next()) {
                lbnome.setText(resultSet.getString("tb03_nome"));
                lbcpf.setText(resultSet.getString("tb03_cpf"));
                lbendereco.setText(resultSet.getString("tb03_endereco"));
                lbnumero.setText(resultSet.getString("tb03_telefone"));
                lbregiao.setText(resultSet.getString("tb03_regiao"));
                lbcheck.setText(resultSet.getString("tb03_dt_reserva"));
                lbcheckout.setText(resultSet.getString("tb03_dt_check"));
                lbnum.setText(resultSet.getString("tb03_numerop"));
                lbtipoquarto.setText(resultSet.getString("tb03_tipo_quarto"));

            }

            banco.desconectar();
            resultSet.close();
            statement.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    
    }//GEN-LAST:event_formWindowOpened

    private void lbcolocacodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbcolocacodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbcolocacodActionPerformed

    private void lbcolocacodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbcolocacodKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            carregaTela();
        }

    }//GEN-LAST:event_lbcolocacodKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbcheck;
    private javax.swing.JLabel lbcheckout;
    private javax.swing.JTextField lbcolocacod;
    private javax.swing.JLabel lbcpf;
    private javax.swing.JLabel lbendereco;
    private javax.swing.JLabel lbfs;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbnum;
    private javax.swing.JLabel lbnumero;
    private javax.swing.JLabel lbregiao;
    private javax.swing.JLabel lbtipoquarto;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    // End of variables declaration//GEN-END:variables
}
